config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "homes#top"
    resources:users
    resources:books
    get 'home/about' => 'homes#about', as: 'about'
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
     belongs_to :user
     has_one_attached:image
     
      validates :title, presence: true,length: { maximum: 20 }
      validates :body, presence: true,length: { maximum: 200 }
      
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_one_attached :profile_image
         has_many :books
        
        validates:name,length: { minimum: 2,maximum:20 },uniqueness: true
        validates:introduction,length: { maximum: 50}
        
        
      def get_profile_image(width = 100, height = 100)
           file_path = Rails.root.join('app/assets/images/no_image.jpg')
        unless profile_image.attached?
            profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
        end
        profile_image.variant(resize_to_limit: [width, height]).processed
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top,:about]
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        user_path(current_user.id)
    end
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit]
  def new
    @book = Book.new
  end
  
  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user = current_user # 投稿したユーザーを設定

    if @book.save
      flash[:notice] = "Book was successfully created."
       redirect_to @book, notice: 'Book was successfully created.'
    else
      @books=Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    
  end

  def show
    @book = Book.find(params[:id])
    @book_new=Book.new
    @user = @book.user   #ここがだめ！bookのuser.IDを入れる
  end
  
  def edit
    @book=Book.find(params[:id])
  end
  
  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to @book
    else
      render :edit
    end
  end
  
  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def get_image
    image.attached? ? image : 'default_image.png'  # Active Storageの場合
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
    def is_matching_login_user
      @book = Book.find(params[:id])
      unless @book.user.id == current_user.id
      redirect_to books_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :authenticate_user!, except: [:top]
  # before_action :configure_permitted_parameters, if: :devise_controller?
  
  def about
  end

  def after_sign_in_path_for(resource)
      books_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit,:update]
  def show
    @user = User.find(params[:id])
    @profile_image = @user.profile_image
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all         # 全てのユーザー
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your profile was successfully updated."
      redirect_to @user
    else
      render :edit
    end
  end
  
  def get_image
    image.attached? ? image : 'default_image.png'  # Active Storageの場合
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
      unless user.id == current_user.id
      redirect_to user_path(current_user)
      end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
<div class="container px-5 px-sm-0">
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class=table>
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
    </tbody>
  </table>
  
    <%=link_to edit_user_path(user) ,class:"btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>
    <% end %>
    
    <h2>New book</h2>
        <%= form_with model: book, local: true do |f| %>
    <h4>title</h4>
        <%= f.text_field :title %>
    <h4>opinion</h4>
        <%= f.text_area :body %>
    <%= f.submit 'Create Book',class: "btn btn-success btn-sm" %>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
        <%= form_with model: @book do |f| %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
          <div>
            <label for="inputTitle">title</label>
            <div><%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"title"%>
            </div>
          </div>
          <div>
            <label for="inputBody">body</label>
            <div><%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"body"%>
            </div>
          </div>
  		  <%= f.submit "Update Book" %>
  		  <% end %>
  		
  		<a>
  		  <%= link_to 'Show', book_path(@book), class: "book_show" %> 
  		</a>
  		|
  		<a class="back" href="/books">Back</a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <div class="container">
  <div class="row">
    <%= render 'left',user:@user,book:@book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            </tr>
          </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                <%= image_tag(book.user.get_profile_image) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %>
              <td><%= book.body %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container">
  <div class="row">
    <%= render 'left',user:@user,book:@book_new %>
    <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
            <tbody>
                <tr>
                  <td><%=image_tag(@book.user.get_profile_image) %>
                  <br>
                  <%= link_to @user.name, user_path(@user.id) %>
                  </br>
                  </td>
                  <td><%= link_to @book.title, book_path(@book.id) %></td>
                  <td><%=@book.body %></td>
                  <% if @book.user == current_user %>
                  <td><a class="btn btn-sm btn-success" href="<%= edit_book_path(@book) %>">Edit</a></td>
                  <td><a data-confirm="本当に消しますか？" class="btn btn-sm btn-danger " rel="nofollow" data-method="delete" href="<%=book_path(@book) %>">Destroy</a></td>
                  <% end %>
                </tr>
            </tbody>
        </table>
    </div>
    </div>
</main>

        

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i><strong>Bookers!</strong>
  </div>
</div>

app/views/homes/top.html.erb
<main>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

        <h1>welcome to<i class="fa-solid fa-book"></i>
        <strong>bookers</strong>!!</h1>

        <p>In<i class="fa-solid fa-book"></i><strong>bookers</strong></p>
        
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
   </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/26164d5121.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="<%= root_path %>">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
      <% if user_signed_in? %>
       <li class="nav-item">
        <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
          <i class="fa-solid fa-house"></i> Home
        <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-users"></i> Users
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to books_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-book-open"></i> Books
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
          <i class="fa-solid fa-right-from-bracket"></i> Log out
          <% end %>
        </li>
        
          <% else %>
           <li class="nav-item">
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <i class="fa-solid fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <i class="fa-solid fa-right-to-bracket"></i>Log in
            <% end %>
          </li>
          </div>
        </div>
      </nav>
    <% end %>
  </header>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
        <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    <%= yield %>
  </body>
  
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>
  
</html>

app/views/users/_leftuser.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class=table>
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
    </tbody>
  </table>
    <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(user) %>"><i class="fa-solid fa-user-gear"></i></a>
    <h2>New book</h2>
        <%= form_with model: book, local: true do |f| %>
    <h4>title</h4>
        <%= f.text_field :title %>
    <h4>opinion</h4>
        <%= f.text_area :body %>
    <%= f.submit 'Create Book',class: "btn btn-success btn-sm" %>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>User info</h1>
        <%= form_with model: @user do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
          <div class="form-group">
              <label for="inputName">Name</label>
              <div><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%></div>
          </div>
          <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          
          <div class="form-group">
              <label for="inputIntroduction">Introduction</label>
              <div><%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction"%></div>
          </div>
  		  <%= f.submit "Update User",class: "btn btn-secondary"  %>
  		  <% end %>
     </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
  <div class="container">
  <div class="row">
    <%= render 'books/left',user:@user,book:@book %>
    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
            <% @users.each do |user| %>
            <tbody>
            <tr>
              <td>
                <%= image_tag(user.get_profile_image) %>
              </td>
              <td><%= user.name %></td>
              <td><%=link_to "Show",user_path(user) %></td>
              <% end %>
            </tr>
            </tbody>
            </thead>
          </table>
    </div>
  </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
  <div class="row">
    <%= render 'books/left',user:@user,book:@book %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
          <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            </tr>
          </thead>
           <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                   <% if book.image %>
                    <%= image_tag(book.user.get_profile_image) %>
                   <% else %>
                    <%= image_tag "default_image.jpg" %>
                   <% end %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %>
                <td><%= book.body %></td>
              </tr>
              <% end %>
            </tbody>
     </table> 
    </div>
  </div>
  </div>
</main>